eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: my-consumer-group
        auto-offset-reset: earliest
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      jackson:
        serialization:
          FAIL_ON_EMPTY_BEANS: false
kafka:
  topic:
    users:
      registration: user-registration
      details-update: user-details-update
    accounts:
      creation: account-creation
    transactions:
      completion: transaction-completion
